name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        impl: [wt_lerp, wt_trunc]
        sampling_rate: [8000, 44100]

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'

      # Install build prerequisites
      # GCC
      - name: Install arm-none-eabi-gcc
        uses: carlosperate/arm-none-eabi-gcc-action@v1
      # GDB
      - name: Install gdb-multiarch
        run: |
          sudo apt-get update
          sudo apt-get install -y gdb-multiarch

      - name: Verify GDB installation
        run: gdb-multiarch --version

      - name: Test GDB Python support
        run: gdb-multiarch --batch -ex "python print('Python support is active!')"

      # Configure and build
      - name: Configure CMake
        run: cmake --preset Debug -DACTIVE_IMPL=${{ matrix.impl }} -DSAMPLING_RATE=${{ matrix.sampling_rate }}

      - name: Build firmware
        run: |
          BUILD_NAME=${{ matrix.impl }}_${{ matrix.sampling_rate }}
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          BUILD_LOG=output/build_$BUILD_NAME.log

          mkdir output
          set -o pipefail
          cmake --build --preset Debug --target f401 | tee output/build_$BUILD_NAME.log

          RAM_USED=$(grep "RAM:" $BUILD_LOG | awk '{print $2}')
          RAM_PCT=$(grep "RAM:" $BUILD_LOG | awk '{print $6}')
          FLASH_USED=$(grep "FLASH:" $BUILD_LOG | awk '{print $2}')
          FLASH_PCT=$(grep "FLASH:" $BUILD_LOG | awk '{print $6}')

          echo "RAM_USED=$RAM_USED" >> $GITHUB_ENV
          echo "RAM_PCT=$RAM_PCT" >> $GITHUB_ENV
          echo "FLASH_USED=$FLASH_USED" >> $GITHUB_ENV
          echo "FLASH_PCT=$FLASH_PCT" >> $GITHUB_ENV

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: firmware_${{ env.BUILD_NAME }}
          path: build/Debug/f401.elf

      # Download Renode
      - name: Cache Renode download
        id: cache-renode
        uses: actions/cache@v4
        with:
          path: ./renode.tar.gz
          key: renode-archive
        
      - name: Download Renode
        if: steps.cache-renode.outputs.cache-hit != 'true'
        run: |
          curl -sSLf -o renode.tar.gz "https://builds.renode.io/renode-latest.linux-portable.tar.gz"

      # Install Python and required packages
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          version: "0.12.23"

      - name: Install Python dependencies
        run: |
          uv venv
          uv pip install 'pyrenode3[all] @ git+https://github.com/antmicro/pyrenode3.git'
          uv pip install matplotlib numpy

      # Run scripts
      - name: Run renode/get_waveform.py
        run: |
          export PYRENODE_PATH=./renode.tar.gz
          uv run python3 renode/get_waveform.py --sampling-rate ${{ matrix.sampling_rate }}

      - name: Run count_instructions.py
        run: |
          export PYRENODE_PATH=./renode.tar.gz
          uv run python3 renode/count_instructions.py --impl-name ${{ matrix.impl }}

      - name: Run plot_spectrum.py
        run: |
          export PYRENODE_PATH=./renode.tar.gz
          uv run python3 plot_spectrum.py output/dump.bin output/spectrum_${{ env.BUILD_NAME }}.png --sampling-rate ${{ matrix.sampling_rate }}

      - name: Upload output artifacts
        uses: actions/upload-artifact@v7
        with:
          name: output_${{ env.BUILD_NAME }}
          path: output/

      - name: Report memory usage
        run: |
          echo "- RAM: ${{ env.RAM_USED }} bytes (${{ env.RAM_PCT }})"
          echo "- FLASH: ${{ env.FLASH_USED }} bytes (${{ env.FLASH_PCT }})"

          echo "### Firmware memory usage" >> $GITHUB_STEP_SUMMARY
          echo "- RAM: ${{ env.RAM_USED }} bytes (${{ env.RAM_PCT }})" >> $GITHUB_STEP_SUMMARY
          echo "- FLASH: ${{ env.FLASH_USED }} bytes (${{ env.FLASH_PCT }})" >> $GITHUB_STEP_SUMMARY
