name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        impl: [wt_lerp, wt_trunc]
        sampling_rate: [8000, 44100]

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'

      # Install build prerequisites
      - name: Install arm-none-eabi-gcc
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      # Configure and build
      - name: Configure CMake
        run: cmake --preset Debug -DACTIVE_IMPL=${{ matrix.impl }} -DSAMPLING_RATE=${{ matrix.sampling_rate }}

      - name: Build firmware
        run: cmake --build --preset Debug --target f401

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: Firmware
          path: build/Debug/f401.elf

      # Download Renode
      - name: Cache Renode download
        id: cache-renode
        uses: actions/cache@v4
        with:
          path: ./renode.tar.gz
          key: renode-archive
        
      - name: Download Renode
        if: steps.cache-renode.outputs.cache-hit != 'true'
        run: |
          curl -sSLf -o renode.tar.gz "https://builds.renode.io/renode-latest.linux-portable.tar.gz"

      # Install Python and required packages
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          version: "0.12.23"

      - name: Install Python dependencies
        run: |
          uv venv
          uv pip install 'pyrenode3[all] @ git+https://github.com/antmicro/pyrenode3.git'
          uv pip install matplotlib numpy

      # Run scripts
      - name: Run renode/get_waveform.py
        run: |
          export PYRENODE_PATH=./renode.tar.gz
          uv run python3 renode/get_waveform.py --sampling-rate ${{ matrix.sampling_rate }}

      - name: Run plot_spectrum.py
        run: |
          export PYRENODE_PATH=./renode.tar.gz
          uv run python3 plot_spectrum.py output/dump.bin output/spectrum.png --sampling-rate ${{ matrix.sampling_rate }}

      - name: Upload output artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Output
          path: output/
